title: Jingying Xu 徐婧颖
logo: /assets/img/wccfl.jpg
#description: Me at WCCFL 42
#show_downlodas: true
theme: jekyll-theme-minimal
nav:
  - title: "Home"
    url: "/"
  - title: "Research"
    url: "/research"
  - title: "Teaching"
    url: "/teaching"
