title: Jingying Xu 徐婧颖
logo: /assets/img/wccfl.jpg
remote_theme: "mmistakes/minimal-mistakes"

# Navigation bar
nav:
  - title: "Home"
    url: /
  - title: "Research"
    url: /research/
  - title: "Teaching"
    url: /teaching/
