title: "Jingying Xu"
logo: /assets/img/wccfl.jpg

remote_theme: mmistakes/minimal-mistakes
minimal_mistakes_skin: default

plugins:
  - jekyll-remote-theme
  - jekyll-include-cache

url: "https://jingyingx.github.io"
baseurl: ""

author:
  name: "徐婧颖 Xú Jìngyǐng [ɕy35 t͡ɕiŋ51 iŋ214]"
  avatar: /assets/img/wccfl.jpg

