title: Jingying Xu 徐婧颖
logo: /assets/img/wccfl.jpg
remote_theme: mmistakes/minimal-mistakes
#description: Me at WCCFL 42
#show_downlodas: true
# Enable navigation
header:
  nav:
    - title: "Home"
      url: "/"
    - title: "Research"
      url: "/research/"
    - title: "Teaching"
      url: "/teaching/"
