title: "Jingying Xu"
logo: /assets/img/wccfl.jpg

remote_theme: mmistakes/minimal-mistakes
minimal_mistakes_skin: default

plugins:
  - jekyll-remote-theme
  - jekyll-include-cache

url: "https://jingyingx.github.io"
baseurl: ""

author:
  name: "Jinging Xu"
  avatar: /assets/img/wccfl.jpg
  

