title: "Jingying Xu"
logo: /assets/img/wccfl.jpg

remote_theme: mmistakes/minimal-mistakes
minimal_mistakes_skin: default

plugins:
  - jekyll-remote-theme
  - jekyll-include-cache

url: "https://jingyingx.github.io"
baseurl: ""

author:
  name: "Jinging Xu"
  avatar: /assets/img/wccfl.jpg
  links:
    links:
    - label: "Email"
      icon: "fas fa-envelope"
      url: "xujing21 at msu.edu"
    - label: "CV"
      icon: "fas fa-file-pdf"
      url: "/jingyingxu-cv_sept_2025.pdf"
     - label: "ResearchGate"
      icon: "fab fa-researchgate"
      url: "https://www.researchgate.net/profile/Jingying-Xu-3/research"
      
      
      
  
  

