title: "Jingying Xu"
logo: /assets/img/wccfl.jpg

remote_theme: mmistakes/minimal-mistakes
minimal_mistakes_skin: default

plugins:
  - jekyll-remote-theme
  - jekyll-include-cache

url: "https://jingyingx.github.io"
baseurl: ""

author:
  name: "Xú, Jìngyǐng [ɕy˧˥ t͡ɕiŋ˥˩ iŋ˨˩˦] 徐婧颖"
  bio: "Email: xujing21 at msu.edu"
  avatar: /assets/img/wccfl.jpg
  links: 
    - label: "CV"
      icon: "fas fa-file-pdf"
      url: "/jingyingxu-cv_sept_2025.pdf"
     
      
      
      
  
  

