title: Jingying Xu 徐婧颖
logo: /assets/img/wccfl.jpg
remote_theme: mmistakes/minimal-mistakes
description: Linguistics | Language Acquisition | Syntax & Semantics
#show_downlodas: true
# Enable navigation
navigation:
    - title: "Home"
      url: "/"
    - title: "Research"
      url: "/research/"
    - title: "Teaching"
      url: "/teaching/"
